server:
  port: 8083
spring:
  application:
    name: commodity-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: 12345
    username: shopdb
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 1000
        min-idle: 0
logging:
  level:
    com.henry.shop.common.base.mapper: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
logstash:
  host: 81.68.167.152