spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: 12345
    username: shopdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    #durid配置
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      stat-view-servlet:
        loginUsername: henry
        login-password: 12345
        url-pattern: /druid/*
        enabled: true
        reset-enable: false
      web-stat-filter:
        enabled: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        url-pattern: /*
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: druid_session
        principal-cookie-name: druid_cookie
logging:
  level:
    com.henry.shop.common.base.mapper: debug


